# docker-compose.yml
version: '3.8'

services:
  # Base de Datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: tenno_db
    restart: always
    networks:
      - tennostore_net
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tennostore_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # Backend Node.js/Express
  backend:
    build: ../Backend
    container_name: tenno_backend
    restart: always
    networks:
      - tennostore_net
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASS: admin
      DB_NAME: tennostore_db
      JWT_SECRET: super_secret_key
    ports:
      - "3000:3000"
    depends_on:
      - db

  # Frontend React/Vite
  frontend:
    build: ../Frontend
    container_name: tenno_frontend
    restart: always
    networks:
      - tennostore_net
    ports:
      - "80:80"
    environment:
      VITE_API_URL: http://localhost:3000

# Definición de la red interna (Bridge)
networks:
  tennostore_net:
    driver: bridge

# Definición del volumen persistente
volumes:
  postgres_data:
