# docker-compose.yml

services:
  # Base de Datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: tenno_db
    restart: always
    networks:
      - tennostore_net
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # Backend Node.js/Express
  backend:
    build: ../Backend
    container_name: tenno_backend
    restart: always
    networks:
      - tennostore_net
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - db

  # Frontend React/Vite
  frontend:
    build: ../Frontend
    container_name: tenno_frontend
    restart: always
    networks:
      - tennostore_net
    ports:
      - "80:80"
    environment:
      VITE_API_URL: ${VITE_API_URL}

# Definición de la red interna (Bridge)
networks:
  tennostore_net:
    driver: bridge

# Definición del volumen persistente
volumes:
  postgres_data:
