# docker-compose.yml
version: '3.8'

services:
  # Base de Datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: tenno_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password_secure
      POSTGRES_DB: tennostore_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Backend Node.js/Express
  backend:
    build: ./Backend
    container_name: tenno_backend
    restart: always
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASS: password_secure
      DB_NAME: tennostore_db
      JWT_SECRET: super_secret_key
    ports:
      - "3000:3000"
    depends_on:
      - db

  # Frontend React/Vite
  frontend:
    build: ./Fronted
    container_name: tenno_frontend
    restart: always
    ports:
      - "80:80"
    environment:
      VITE_API_URL: http://localhost:3000

volumes:
  postgres_data:
